### ISSUE TITLE
long-lived failures can generate unhandled exceptions

### ISSUE THREAD

**Issue by kurttheviking** [kurttheviking/orchard-js#7]
e.g.

```
Unhandled rejection Error: DEL can't be processed. The connection has already been closed.
    at RedisClient.send_command (/project/node_modules/orchard/node_modules/redis/index.js:788:23)
    at RedisClient.(anonymous function).RedisClient.(anonymous function) (/project/node_modules/orchard/node_modules/redis/index.js:966:25)
    at RedisClient.tryCatcher (/project/node_modules/orchard/node_modules/bluebird/js/release/util.js:16:23)
    at RedisClient.ret (eval at <anonymous> (/project/node_modules/orchard/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:13:23)
    at remove (/project/node_modules/orchard/index.js:194:20)
    at tryCatcher (/project/node_modules/orchard/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/project/node_modules/orchard/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/project/node_modules/orchard/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/project/node_modules/orchard/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/project/node_modules/orchard/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/project/node_modules/orchard/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/project/node_modules/orchard/node_modules/bluebird/js/release/async.js:135:10)
    at Async.drainQueues (/project/node_modules/orchard/node_modules/bluebird/js/release/async.js:16:14)
    at process._tickCallback (node.js:458:13)
```

orchard should catch these errors and emit them but allow any through-bound request to continue

**Comment by kurttheviking** [comment]
closing as expected for long-lived delete failures
